---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copying Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ real_user_home }}/.tmux.conf"
    owner: "{{ real_user }}"
    group: "{{ real_user }}"
    mode: '0644'
  become: true


