---
- name: Add NOPASSWD rule for the current user
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ real_user }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: real_user != 'root'
  with_items:
    - "{{ real_user }}\tALL=(ALL) NOPASSWD:ALL"